src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $all_day = null;

    #[ORM\Column(length: 7, nullable: true)]
    private ?string $background_color = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(?string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('start', DateTimeType::class, [
                'date_widget' => 'single_text'
            ]
            )
            ->add('end', DateTimeType::class, [
                    'date_widget' => 'single_text'
            ])
            ->add('description')
            ->add('all_day')
            ->add('background_color', ColorType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reservation')]
class BookingController extends AbstractController
{
    #[Route('/', name: 'app_booking_index', methods: ['GET'])]
    public function index( BookingRepository $bookingRepository): Response
    {
        $events = $bookingRepository->findAll();

        dump($events);

        $rdvs = [];

        foreach ($events as $event) {
            $rdvs[] = [
                'id' => $event->getId(),
                'title' => $event->getTitle(),
                'description' => $event->getDescription(),
                'start' => $event->getStart()->format('Y-m-d H:i:s'),
                'end' => $event->getEnd()->format('Y-m-d H:i:s'),
                'allDay' => $event->isAllDay(),
                'backgroundcolor' => $event->getBackgroundColor(),
            ];
        }

        $data = json_encode($rdvs);

        return $this->render('booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
            'data' => $data,
        ]);
    }


    #[Route('/chambre', name: 'app_booking_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BookingRepository $bookingRepository): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookingRepository->save($booking, true);

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_show', methods: ['GET'])]
    public function show(Booking $booking): Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_booking_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Booking $booking, BookingRepository $bookingRepository): Response
    {
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookingRepository->save($booking, true);

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_delete', methods: ['POST'])]
    public function delete(Request $request, Booking $booking, BookingRepository $bookingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $booking->getId(), $request->request->get('_token'))) {
            $bookingRepository->remove($booking, true);
        }

        return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('app_booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/booking/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer sa reservation') }}</button>
<a class="btnAjoutCart" href="{{ path('cart_add_booking') }}"><i class="fa-solid fa-cart-plus"></i> Ajouter au Panier</a>

{{ form_end(form) }}

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Booking{% endblock %}

{% block body %}
    <h1>Edit Booking</h1>

    {{ include('booking/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_booking_index') }}">back to list</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking index{% endblock %}

{% block main %}


    {% include('partials/_calendar.html.twig') %}

    {{ dump(bookings) }}

    <h1>Booking index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Start</th>
                <th>End</th>
                <th>Description</th>
                <th>All_day</th>
                <th>Background_color</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.title }}</td>
                <td>{{ booking.start ? booking.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ booking.end ? booking.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ booking.description }}</td>
                <td>{{ booking.allDay ? 'Yes' : 'No' }}</td>
                <td>{{ booking.backgroundColor }}</td>
                <td>
                    <a href="{{ path('app_booking_show', {'id': booking.id}) }}">show</a>
                    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{#    {{data|raw}}#}
    <a href="{{ path('app_booking_new') }}">Create new</a>

{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Reservation{% endblock %}

{% block main %}

    <h1>Nouvelle reservation pour une chambre</h1>

    {{ include('booking/_form.html.twig') }}
    {% include('partials/_login.html.twig') %}

    <a href="{{ path('app_booking_index') }}">back to list</a>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking{% endblock %}

{% block body %}
    <h1>Booking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ booking.title }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ booking.start ? booking.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ booking.end ? booking.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ booking.description }}</td>
            </tr>
            <tr>
                <th>All_day</th>
                <td>{{ booking.allDay ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ booking.backgroundColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_booking_index') }}">back to list</a>

    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}